### ISSUE TITLE
possible bug in registering handlers

### ISSUE THREAD

**Issue by cjrpriest** [JamesRandall/AzureFromTheTrenches.Commanding#1]
Please see this gist for a repo - https://gist.github.com/cjrpriest/b536bb69630fd8ff60b1e0089b5abae1

I get this exception thown on line 37:

```
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at AzureFromTheTrenches.Commanding.Implementation.CommandExecuter.<ExecuteCommandWithHandlers>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AzureFromTheTrenches.Commanding.Implementation.CommandExecuter.<ExecuteAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at AzureFromTheTrenches.Commanding.Implementation.CommandExecuter.<ExecuteAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AzureFromTheTrenches.Commanding.Implementation.CommandDispatcher.<DispatchAsync>d__6`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AzureFromTheTrenches.Commanding.Implementation.CommandDispatcher.<DispatchAsync>d__5.MoveNext()
```

Thanks :)

**Comment by JamesRandall** [comment]
Definitely a bug. Thanks for reporting it.

As part of the optimisation work I'd introduced an issue not caught by the unit tests. This is fixed in 6.1.1 that is publishing to NuGet now. I've also created this gist that demonstrates it working:

https://gist.github.com/JamesRandall/87c31114ebde542f82cbb9c2fe2ae7c6

Its something that would easily have been caught by some acceptance tests so you can imagine what my job for the weekend / train journey is!

If you get any further issues please let me know!
